#!/usr/bin/env node
/* ══════════════════════════════════════════════════════════════
   og.js — the social sharing cards
   ══════════════════════════════════════════════════════════════

   WHY THIS EXISTS AT ALL

   The site shipped with `og:image` pointing at `assets/og.svg`. It was
   a perfectly good 1200×630 card and no link preview anywhere ever
   rendered it: **no major scraper rasterizes SVG.** Facebook (which
   LinkedIn's and most others' crawlers imitate), X, Slack, Discord and
   Apple's iMessage fetcher all accept PNG / JPEG / GIF / WEBP and
   silently drop anything else. A vector card is not a small card or a
   slow card — it is no card, and the link degrades to bare blue text.

   So the deliverable is raster. This script renders each card to PNG
   through headless Chrome, which gets us the site's real web fonts
   (Newsreader + Libre Franklin) instead of a system-serif approximation.

   WHY THE CARDS ARE STATIC AND COMMITTED

   Everything else under `scripts/` is regenerated by CI on every run.
   These are not, deliberately: rendering needs a browser binary, and
   `news.yml` should not grow a Chrome install to redraw artwork whose
   text — a section name and the masthead — does not change between
   runs. The *page-specific* half of a preview card (the headline and
   the blurb the platform prints beside the image) comes from
   `og:title` / `og:description`, which seo.js already writes per page.
   The image carries the brand and the section.

   That is why there is one card per *page type*, not per page:
   ~200 company pages sharing one "Companies" card is the same trade
   every newsroom makes with its section fronts.

   REGENERATING

     node scripts/og.js          # rewrites assets/og/*.png

   Run it after changing the design, the palette, or the card list —
   then commit the PNGs. seo.js does not invoke it; a build with no
   Chrome present must still produce pages.
   ══════════════════════════════════════════════════════════════ */

const fs = require("fs");
const os = require("os");
const path = require("path");
const { execFileSync } = require("child_process");
const { TAXONOMY, FALLBACK_TAG, topicSlug } = require("./taxonomy");

const ROOT = path.join(__dirname, "..");
const OUT = path.join(ROOT, "assets", "og");

/* 1200×630 is the 1.91:1 that Facebook, LinkedIn and X all document,
   and the one iMessage crops least aggressively. Below 600×315 several
   platforms downgrade a `summary_large_image` card to the small square
   variant, so this is a floor as much as a size. */
const W = 1200;
const H = 630;

/* Same ink as style.css :root — the card is the site's front step. */
const C = {
  paper: "#f7f4ee",
  paper2: "#efeae0",
  ink: "#1c1a15",
  ink2: "#45413a",
  ink3: "#837d70",
  rule: "rgba(28, 26, 21, 0.16)",
  ruleSoft: "rgba(28, 26, 21, 0.09)",
  accent: "#9a2b1e",
};

const DOMAIN = "insurtechdaily.io";

/* ── The card list ──────────────────────────────────────────────
   `id` is the filename stem and the key seo.js looks pages up by.
   Keep the two in sync through cardFor() below — never spell a
   filename out at a call site. */
const BASE_CARDS = [
  {
    id: "home",
    eyebrow: "The wire",
    title: "Insurtech Daily",
    sub: "Funding, deals, launches and platform moves — aggregated all day.",
    kicker: "Refreshed three times daily",
  },
  {
    id: "brief",
    eyebrow: "Published each morning",
    title: "The Brief",
    sub: "What moved in insurtech, and what it means.",
    kicker: "Archived daily",
  },
  {
    id: "funding",
    eyebrow: "Deal tracker",
    title: "Insurtech Funding",
    sub: "Every round, deduplicated across every outlet covering it.",
    kicker: "Amount · stage · lead investor",
  },
  {
    id: "companies",
    eyebrow: "The index",
    title: "Companies",
    sub: "Every company tracked across Insurtech Daily's coverage.",
    kicker: "Searchable · one page each",
  },
  {
    id: "company",
    eyebrow: "Company profile",
    title: "Company Coverage",
    sub: "Every story, funding round and partner we've recorded.",
    kicker: `${DOMAIN}/company`,
  },
  {
    id: "topics",
    eyebrow: "Browse by subject",
    title: "Topics",
    sub: "Insurtech coverage sorted into the categories that move it.",
    kicker: "Fourteen hubs · built from the archive",
  },
  {
    // One card for the glossary index and every term page, the way
    // ~1,300 company pages share the "company" card — the per-page half
    // of a preview is og:title/og:description, which head() writes.
    id: "glossary",
    eyebrow: "Glossary",
    title: "Insurance Terms",
    sub: "What the vocabulary in insurtech headlines actually means.",
    kicker: `${DOMAIN}/glossary`,
  },
  {
    // One card for the market index and every country page — the same
    // per-type sharing the company and glossary cards use.
    id: "market",
    eyebrow: "By market",
    title: "Insurtech Markets",
    sub: "Who is building insurance where, and what they have raised.",
    kicker: `${DOMAIN}/market`,
  },
  {
    // One card for the sector index and every line-of-business page,
    // the sibling axis to "market" and sharing its treatment.
    id: "sector",
    eyebrow: "By sector",
    title: "Insurtech Sectors",
    sub: "Who sells which kind of insurance, and what they have raised.",
    kicker: `${DOMAIN}/sector`,
  },
];

/* One card per topic hub, named for the same slug that builds the URL,
   so /topic/cyber/ can only ever reach og/topic-cyber.png. */
const TOPIC_CARDS = [...TAXONOMY.map(([name]) => name), FALLBACK_TAG].map((name) => ({
  id: `topic-${topicSlug(name)}`,
  eyebrow: "Topic",
  title: name,
  sub: `Insurtech ${name.toLowerCase()} coverage, updated through the day.`,
  kicker: `${DOMAIN}/topic/${topicSlug(name)}`,
}));

const CARDS = [...BASE_CARDS, ...TOPIC_CARDS];
const IDS = new Set(CARDS.map((c) => c.id));

/* ── The lookup every consumer uses ─────────────────────────────
   Falls back to the home card rather than to a missing file: a page
   with the wrong card still previews, a page with a 404 image
   previews as bare text, which is the bug this file exists to fix. */
function cardFor(id) {
  return `/assets/og/${IDS.has(id) ? id : "home"}.png`;
}

/* ══════════════════════════════════════════════════════════════
   RENDERING
   ══════════════════════════════════════════════════════════════ */

const esc = (s = "") =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/* Headlines are set by hand here, so a size table beats a measuring
   pass: the longest title in the list is "Claims & Underwriting". */
function titleSize(t) {
  const n = t.length;
  if (n <= 14) return 112;
  if (n <= 20) return 94;
  if (n <= 26) return 80;
  return 68;
}

function cardHtml(card) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@400;500;600;700&family=Newsreader:opsz,wght@6..72,500;6..72,600&display=swap" rel="stylesheet">
<style>
  html, body { margin: 0; padding: 0; }
  body {
    width: ${W}px; height: ${H}px; overflow: hidden;
    background: ${C.paper};
    font-family: "Libre Franklin", Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    font-feature-settings: "kern" 1, "liga" 1;
  }
  /* The masthead rule. Same gesture as the site's top border, scaled
     to a card that gets looked at for half a second in a chat thread. */
  .bleed { position: absolute; inset: 0 0 auto 0; height: 14px; background: ${C.accent}; }
  .frame {
    position: absolute; inset: 14px 0 0 0;
    padding: 62px 84px 60px;
    display: flex; flex-direction: column;
  }
  /* Masthead ------------------------------------------------ */
  .masthead { display: flex; align-items: center; gap: 16px; }
  .tick { width: 9px; height: 40px; background: ${C.accent}; }
  .wordmark {
    font-size: 27px; font-weight: 700; letter-spacing: .18em;
    text-transform: uppercase; color: ${C.ink};
  }
  .rule { margin-top: 30px; height: 1px; background: ${C.rule}; }
  /* Body ---------------------------------------------------- */
  .body { flex: 1; display: flex; flex-direction: column; justify-content: center; }
  .eyebrow {
    font-size: 24px; font-weight: 600; letter-spacing: .17em;
    text-transform: uppercase; color: ${C.accent};
    margin-bottom: 24px;
  }
  h1 {
    margin: 0;
    font-family: "Newsreader", Georgia, serif;
    font-weight: 600; font-size: ${titleSize(card.title)}px;
    line-height: 1.04; letter-spacing: -0.015em; color: ${C.ink};
  }
  .sub {
    margin-top: 26px; max-width: 880px;
    font-family: "Newsreader", Georgia, serif;
    font-size: 34px; font-weight: 400; line-height: 1.32; color: ${C.ink2};
  }
  /* Footer -------------------------------------------------- */
  .foot {
    display: flex; align-items: center; justify-content: space-between;
    padding-top: 26px; border-top: 1px solid ${C.ruleSoft};
    font-size: 22px; color: ${C.ink3};
  }
  .domain { font-weight: 600; color: ${C.ink2}; letter-spacing: .01em; }
  .kicker { display: flex; align-items: center; gap: 12px; }
  .dot { width: 10px; height: 10px; border-radius: 50%; background: ${C.accent}; }
</style></head>
<body>
  <div class="bleed"></div>
  <div class="frame">
    <div>
      <div class="masthead">
        <div class="tick"></div>
        <div class="wordmark">Insurtech Daily</div>
      </div>
      <div class="rule"></div>
    </div>
    <div class="body">
      <div class="eyebrow">${esc(card.eyebrow)}</div>
      <h1>${esc(card.title)}</h1>
      <div class="sub">${esc(card.sub)}</div>
    </div>
    <div class="foot">
      <div class="domain">${esc(DOMAIN)}</div>
      <div class="kicker"><span class="dot"></span>${esc(card.kicker)}</div>
    </div>
  </div>
</body></html>`;
}

/* The square mark, for the `logo` slot in Organization JSON-LD.
   Google asks for a raster there too, and a 1.91:1 news card is the
   wrong shape for a logo even when it is the right format. */
function logoHtml(size = 512) {
  const u = size / 512;
  return `<!doctype html>
<html><head><meta charset="utf-8"><style>
  html, body { margin: 0; padding: 0; }
  body { width: ${size}px; height: ${size}px; background: ${C.paper}; position: relative; }
  i { position: absolute; display: block; }
  .bar  { left: ${112 * u}px; top: ${133 * u}px; width: ${41 * u}px; height: ${256 * u}px; background: ${C.accent}; }
  .l1   { left: ${195 * u}px; top: ${174 * u}px; width: ${205 * u}px; height: ${36 * u}px; background: ${C.ink}; }
  .l2   { left: ${195 * u}px; top: ${251 * u}px; width: ${205 * u}px; height: ${26 * u}px; background: ${C.ink3}; }
  .l3   { left: ${195 * u}px; top: ${307 * u}px; width: ${143 * u}px; height: ${26 * u}px; background: ${C.ink3}; }
</style></head><body>
  <i class="bar"></i><i class="l1"></i><i class="l2"></i><i class="l3"></i>
</body></html>`;
}

/* Chrome, wherever this machine keeps it. Linux names come first so a
   CI shell can render too if someone ever wants that; macOS is where
   this is actually run. */
const CHROME_CANDIDATES = [
  process.env.CHROME_PATH,
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  "/Applications/Chromium.app/Contents/MacOS/Chromium",
  "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
  "/usr/bin/google-chrome",
  "/usr/bin/chromium-browser",
  "/usr/bin/chromium",
].filter(Boolean);

function findChrome() {
  for (const p of CHROME_CANDIDATES) if (fs.existsSync(p)) return p;
  return null;
}

function shoot(chrome, html, out, w, h) {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "og-"));
  const page = path.join(tmp, "card.html");
  fs.writeFileSync(page, html);
  try {
    execFileSync(
      chrome,
      [
        "--headless",
        "--disable-gpu",
        "--no-sandbox",
        "--hide-scrollbars",
        "--force-device-scale-factor=1",
        // Web fonts are fetched over the network; without a virtual-time
        // budget Chrome screenshots the fallback serif and the card ships
        // looking like a default browser page.
        "--virtual-time-budget=10000",
        `--window-size=${w},${h}`,
        `--screenshot=${out}`,
        `file://${page}`,
      ],
      { stdio: ["ignore", "ignore", "pipe"] }
    );
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
}

function build() {
  const chrome = findChrome();
  if (!chrome) {
    console.error(
      "  ! no Chrome/Chromium found — set CHROME_PATH to a browser binary.\n" +
        "    Cards are committed PNGs; the existing ones stay valid until this runs."
    );
    process.exit(1);
  }
  fs.mkdirSync(OUT, { recursive: true });
  console.log(`\nSocial cards → assets/og/  (${path.basename(chrome)})\n`);

  let bytes = 0;
  for (const card of CARDS) {
    const out = path.join(OUT, `${card.id}.png`);
    shoot(chrome, cardHtml(card), out, W, H);
    const size = fs.statSync(out).size;
    bytes += size;
    console.log(`  ✓ ${card.id}.png`.padEnd(34) + `${(size / 1024).toFixed(0)} KB`);
  }

  const logo = path.join(ROOT, "assets", "logo.png");
  shoot(chrome, logoHtml(512), logo, 512, 512);
  console.log(`  ✓ logo.png (512×512)`.padEnd(34) + `${(fs.statSync(logo).size / 1024).toFixed(0)} KB`);

  console.log(
    `\n  ${CARDS.length} cards at ${W}×${H}, ${(bytes / 1024).toFixed(0)} KB total\n`
  );
}

module.exports = { cardFor, CARDS, W, H, OUT };

if (require.main === module) build();
